---
services:
  ace:
    image: ghcr.io/martinbjeldbak/acestream-http-proxy
    container_name: acestream-http-proxy
    ports:
      - "127.0.0.1:6878:6878"
      - "8621:8621"
    expose:
      - "6878" # This makes the base url "http://ace:6878"

  rproxy:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/kism/acestream-webplayer
    container_name: acestream-webplayer
    volumes:
      - ./private:/app/private # Ensure that these arent symlinks
      - ./Rocket.toml:/app/Rocket.toml # This is your config
    ports:
      - "443:443"
    depends_on:
      - ace
