## defaults for _all_ profiles
[default]
address = "0.0.0.0"
limits = { form = "64 kB", json = "1 MiB" }
ace_base_url = "http://localhost:6878"
external_base_url = "http://localhost:8999"
ace_stream_id = "7da08fcda6fa43a39aca9be65dabf054164eaac1"
stream_password = "secret"
transcode_audio = false # Seems to not work

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
port = 8999

## set only when compiled in release mode, i.e, `cargo build --release`
[release]
port = 443

[release.tls]
certs = "private/fullchain.cer"
key = "private/cert.key"
